###
GET http://localhost:8080/admin/demo

###
GET http://localhost:8080/system/email/sendHtml

###
GET http://localhost:8080/admin/dashboard

###
GET http://localhost:8080/registration/api/get-address

### Delete
GET http://localhost:8080/search/deleteAll

### Convert
GET http://localhost:8080/search/convert

### Delete search
DELETE http://localhost:9200/products

